src/Entity/ManiaplanetUser.php
<?php
/**
 * ManiaplanetUser.php
 * 
 * @author     Martin Weber <enwi2@t-online.de>
 * @copyright  2018 Martin Weber
 * @license    https://www.gnu.org/licenses/gpl.txt  GNU GPL v3
 * @link       https://github.com/askuri/maniaplanet-oauth-symfony
 */

namespace App\Entity;

use App\Security\OAuth2\ManiaplanetResourceOwner;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ManiaplanetUserRepository")
 * @ORM\Table(name="maniaplanet_user", 
 *    uniqueConstraints={
 *        @ORM\UniqueConstraint(name="login",
 *            columns={"login"})
 *    }
 * )
 */
class ManiaplanetUser implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $login;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $nickname;

    /**
     * @ORM\Column(type="string", length=191, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $role;

    /**
     * @ORM\Column(type="boolean")
     */
    private $email_send_approval_notification;

    public function getUserIdentifier() {
        return $this->login;
    }

    /**
     * @deprecated remove with Symfony 6, getUserIdentifier is the replacement
     */
    public function getUsername()
    {
        return $this->login;
    }
    
    public function getRoles()
    {
        //return $this->roles;
        return array($this->role);
    }

    public function getSalt()
    {
        // we don't need a salt as we are using a token
        return null;
    }

    public function getPassword()
    {
        // we are using tokens, no passwords
        return "";
    }
    
    public function eraseCredentials()
    {
    }
    
    /**
     * Update the properties.
     * Used when user logs in to update the database (e.g. email has changed)
     * Returns true if any of the vars below has changed its value (triggers db update)
     * 
     * @param ManiaplanetResourceOwner $maniaplanetUser
     * @return boolean
     */
    public function updateFromManiaplanetUser(ManiaplanetResourceOwner $maniaplanetUser) {
        $change = false;
        
        if ($this->email != $maniaplanetUser->getEmail()) {
            $this->email = $maniaplanetUser->getEmail();
            $change = true;
        }
        
        if ($this->nickname != $maniaplanetUser->getNickname()) {
            $this->nickname = $maniaplanetUser->getNickname();
            $change = true;
        }
        
        return $change;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }
    
    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->login,
            $this->nickname,
            $this->email,
        ));
    }
    
    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->login,
            $this->nickname,
            $this->email,
        ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function getEmailSendApprovalNotification(): ?bool
    {
        return $this->email_send_approval_notification;
    }

    public function setEmailSendApprovalNotification(bool $email_send_approval_notification): self
    {
        $this->email_send_approval_notification = $email_send_approval_notification;

        return $this;
    }
}

src/Entity/Path.php
<?php
/**
 * This class represents all paths to user content files, always relative
 * to the root of the user folders. So the first atom is the login.
 * 
 * It also automatically makes sure that it never points to an item outside the
 * base path UPLOAD_DIR (from env).
 */

namespace App\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Webmozart\PathUtil\Path as PU;

class Path {
    /**
     * A path is stored as a canonicalized (normalized) array with each atom
     * of the path being one key of the array.
     * Root path is represented by a one-key array with the value being an empty
     * string.
     */
    private $path;
    
    // metadata for usage by other classes, not used in this class
    /**
     * @var bool true if the file is / should be blocked
     */
    private $blocked;
    
    /**
     * @var bool true if the file is / should be deleted
     */
    private $delete;
    
    public function __construct() {
        
    }
    
    public function setBlocked(bool $var) {
        $this->blocked = $var;
    }
    
    public function getBlocked(): bool {
        return $this->blocked;
    }
    
    public function setDelete(bool $var) {
        $this->delete = $var;
    }
    
    public function getDelete(): bool {
        return $this->delete;
    }
    
    /**
     * Set the path from a given string.
     * Attention: starting '/' causes an empty first atom and
     * owner checks will fail and much more.
     * This should only be used once on one object!
     * It is usually expected, that this is relative to PUBLIC_UPLOAD_URL 
     * 
     * @param string $s
     * @throws \Exception
     */
    public function fromString(string $s): void {
        $s = trim($s, '/');
        $s = self::cleanPath($s, true);
        $this->path = explode('/', PU::canonicalize($s));
        if (!$this->isLegal()) {
            throw new \Exception('A path was provided to App\Entity\Path that is not inside the base path / upload directory. Path is: '.$s);
        }
    }
    
    
    /**
     * Get the string representation of this path.
     * 
     * @return string
     */
    public function getString(): string {
        $s = implode('/', $this->path);
        return $s;
    }
    
    /**
     * Get the i'th atom of the path.
     * You may use negative numbers for a wrap around.
     * E.g -1 gives the last element, -2 the second last.
     * 
     * @param int $i
     * @return string|null
     */
    public function getAtom(int $i): ?string {
        // positive $i
        if ($i >= 0 && isset($this->path[$i])) {
            return $this->path[$i];
        }
        // negative: wrap around
        elseif ($i < 0 && isset($this->path[count($this->path)+$i])) {
            return $this->path[count($this->path)+$i];
        }
        else {
            return null;
        }
    }
    
    public function getArray(): array {
        return $this->path;
    }

    /**
     * Gives a new path object that points to the directory
     * $n levels above the current one.
     * If $n exceeds the depth of the path it returns the root.
     * examples
     * $n = -1 (default) means the immediate parent path,
     * $n = 1 is the uppermost folder's path,
     * $n = 2 is the second path
     * $n > depth will return the full path
     * 
     * @param int $n
     * @return Path
     * @throws \Exception
     */
    public function getParentPath(int $n = -1): self {
        $parent = clone $this;
        
        $parent->path = array_slice($this->path, 0, $n);
        
        return $parent;
    }
    
    /**
     * Returns the URL the file can be reached with according to 
     * the correspondent env var.
     * 
     * @return string
     */
    public function getPublicURL(): string {
        return PU::join($_ENV['PUBLIC_UPLOAD_URL'], $this->getString());
    }
    
    /**
     * Gives the full path in the file system.
     * Depends on the UPLOAD_DIR env var.
     * 
     * @return string
     */
    public function getAbsolutePath(): string {
        return PU::join($_ENV['UPLOAD_DIR'], $this->getString());
    }
    
    /**
     * Return the depth of the path
     * Examples:
     * 0: is root folder
     * 1: foo
     * 2: /foo, foo/, foo/bar
     * 
     * @return int
     */
    public function getDepth(): int {
        if ($this->isRoot()) {
            return 0;
        }
        else {
            return count($this->path);
        }
    }
    
    /**
     * Returns a cloned object with a single atom appended to the path.
     * 
     * @param string $with
     * @param bool $acceptslashes true if slashes should not be stripped (default false)
     * @return Path a clone of $this
     * @throws \Exception
     */
    public function append(string $with, bool $acceptslashes = false): self {
        if (!$acceptslashes && strpos($with, '/')) {
            throw new \Exception('Paths may only be appended with atoms. No slashes allowed.');
        }
        
        $with = self::cleanPath($with, $acceptslashes);
        
        $clone = clone $this;
        $clone->path[] = $with;
        return $clone;
    }
    
    /**
     * Check if the given user is allowed to write
     * 
     * @param UserInterface $user
     * @return boolean
     */
    public function isWritableBy(UserInterface $user): bool {
        // banned users simply never write anywhere
        if (true === in_array('ROLE_BANNED', $user->getRoles())) {
            return false;
        }
        
        return (
            true === in_array('ROLE_ADMIN', $user->getRoles()) ||
            $user->getUsername() == $this->getOwnerLogin()
        );
    }
    
    /**
     * Gets the owner (login) this path (operates on the object only).
     * This might give you a string that is not a valid login.
     * Returns an empty string if it's the root folder
     * 
     * @return string
     */
    public function getOwnerLogin(): string {
        return $this->getAtom(0);
    }
    
    /**
     * Checks if the path is pointing to a folder inside the base path.
     * 
     * @return bool
     */
    public function isLegal(): bool {
        // empty path / root only is legal
        if ($this->isRoot()) {
            return true;
        }
        
        // make sure that our path doesn't go "upwards"
        // Workaround: isBasePath doesn't work if the first argument is ./
        // so we have to prefix some nonsense to both folders
        return PU::isBasePath('./ihatebugs', './ihatebugs/'.$this->getString());
    }
    
    /**
     * True if path is root folder
     * 
     * @return bool
     */
    public function isRoot(): bool {
        return $this->path == [''];
    }
    
    /**
     * Removes special chars and replaces them with underscore.
     * 
     * @param string $path
     * @param bool $acceptslashes
     * @return string
     */
    public static function cleanPath(string $path, bool $acceptslashes): string {
        if ($acceptslashes) {
            return preg_replace('/[^A-Za-z0-9-._\/]/', '_', $path);
        }
        else {
            return preg_replace('/[^A-Za-z0-9-._]/', '_', $path);
        }
    }
    
    /**
     * Returns true if the path points to a directory
     * 
     * @return bool
     */
    public function isDir(): bool {
        return is_dir($this->getAbsolutePath());
    }
    
    /**
     * If the path points to a file, return its size.
     * If it's not a file or does not exist, return false.
     * 
     * @return int, false on error
     */
    public function getFileSize() {
        return filesize($this->getAbsolutePath());
    }
}

templates/browse/components/browser.html.twig
{# convert bytes in a human readable way #}
{% import "macros/bytes.html.twig" as bytes %}

<form method="post" action="{{ app.request.uri }}">
    <input type="hidden" name="token" value="{{ csrf_token('browse_block-delete') }}" />
    <input type="hidden" name="submit_block-delete" value="true" />
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Size</th>
                <th>Approved</th>
                <th>Delete</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
            {% for item in list %}
                {% set block_disabled = not is_granted('ROLE_ADMIN') ? 'disabled' %}
                <tr>
                    <!-- name -->
                    <td>
                        {% if item.attributes.isDir %}
                            <a style="display:block; width:100%;" 
                                href="{{ app.request.pathinfo ~ '?path=' ~ item.path.getString }}">
                                <span class="glyphicon glyphicon-folder-close"></span> {{ item.path.getBaseName|e }} {# todo #}
                            </a>
                        {% else %}
                            <span class="glyphicon glyphicon-file"></span> {{ item.path.getBaseName|e }} {# todo #}
                        {% endif %}
                    </td>

                    <!-- size -->
                    <td>
                        {{ not item.attributes.isDir ? bytes.humanReadableBytes(item.attributes.fileSize) }}
                    </td>

                    <!-- block -->
                    <td>
                        {% if item.attributes.isFile %}
                            <input type="radio" {{ item.is_blocked ? 'checked' }} {{ block_disabled }} name="block[{{ item.path.getString }}]" value="true">&nbsp;no
                            <input type="radio" {{ item.is_blocked ? 'checked' }} {{ block_disabled }} name="block[{{ item.path.getString }}]" value="false">&nbsp;yes
                        {% endif %}
                    </td>

                    <!-- delete -->
                    <td>
                        {% if item.path.isWritableBy(app.user) %}
                            <input type="checkbox" name="delete[{{ item.path.getString }}]" value="true">
                        {% endif %}
                    </td>

                    <!-- download -->
                    <td>
                        {% if item.attributes.isFile %}
                            {% if item.is_blocked %}
                                <a class="btn btn-xs disabled" role="button" style="pointer-events: auto;"
                                    title="Usually takes <24h" data-toggle="tooltip" data-placement="auto left"
                                    href="{{ item.path.getPublicUrl }}" {# todo fix href #}
                                ><i class="glyphicon glyphicon-time"></i> Awaiting approval</a>
                            {% else %}
                                <a class="btn btn-info btn-xs" role="button" style="width:100%;"
                                    href="{{ item.path.getPublicUrl }}" {# todo fix href #}
                                ><span class="glyphicon glyphicon-link"></span> Link</a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <div class="alert alert-info">
                    There is nothing here yet.
                </div>
            {% endfor %}
        </tbody>
    </table>
        
    {% if path.isWritableBy(app.user) %}
        <div class="well well-sm text-right">
            <button type="submit" name="block-delete" class="btn btn-primary">
                {{ is_granted('ROLE_ADMIN') ? '<i class="glyphicon glyphicon-ok"></i> Update approval / delete' : '<span class="glyphicon glyphicon-trash"></span> Delete selected' }}
            </button>
        </div>
    {% endif %}
</form>

{% block javascripts %}
    <!-- enable bootstrap toolstips -->
    <script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();   
        });
    </script>
{% endblock %}

templates/browse/components/browser_header.html.twig
<div class="well well-sm" style="display: flex;">
    <a href="{{ app.request.pathinfo ~ '?path=/' ~ path.getParentPath.getString }}" class="btn btn-primary">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> Back
    </a>
        
    &nbsp;
    
    <a href="{{ app.request.uri }}" class="btn btn-default">
        <span class="glyphicon glyphicon-refresh"></span> Refresh
    </a>

    &nbsp;
    {#
    <a href="{{ app.request.pathinfo ~ '?path=/' ~ app.user.username }}" class="btn btn-default">
        <span class="glyphicon glyphicon-user"></span> My files 
    </a>

    &nbsp; #}
    
    <a href="{{ path('browser_locs_download') }}?path={{ path.getString }}"
        style="margin-bottom: 0px"
        class="btn btn-default">
        <span class="glyphicon glyphicon-download-alt"></span> .loc files
    </a>
    
    <ul class="breadcrumb" style="margin-bottom: 0px">
        {% set depth = path.getDepth %}
        <li><a href="{{ app.request.pathinfo ~ '?path=/' }}"><span class="glyphicon glyphicon-home"></span></a></li>
        {% for i in 0..depth %}
            <li><a href="{{ app.request.pathinfo ~ '?path=/' ~ path.getParentPath(i+1).getString() }}">{{ path.getAtom(i) }}</a></li>
        {% endfor %}
    </ul>
</div>

    

templates/browse/components/infoboxes.html.twig
{% for type, messages in app.session.flashbag.all() %}
    {% for message in messages %}
        <div class="alert alert-{{ type }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            {{ message|raw }}
        </div>
    {% endfor %}
{% endfor %}

templates/browse/components/newfolder.html.twig
<form method="post" action="{{ app.request.uri }}" class="form-inline">
    <div style="margin-bottom: 0px">
        <div class="form-group">
            <input type="hidden" name="token" value="{{ csrf_token('browse_newfolder') }}" />
            <label for="newdir">Create Folder: </label>
            <input name="newdir" id="newdir" type="text" class="form-control input-sm">
        </div>
        <button type="submit" class="btn btn-default btn-sm">Create</button>
    </div>
</form>

templates/browse/components/upload.html.twig
{% block stylesheets %}
<link href="{{ asset('css/dropzone.css') }}" rel="stylesheet" />
<link href="{{ asset('css/dropzone_basic.css') }}" rel="stylesheet" />
{% endblock %}

{% block body %}
    <form action="{{ oneup_uploader_endpoint('browse') }}" class="dropzone" id="upload-browse">
        <input name="path" value="{{ path.string }}" hidden>
    </form>

    <!-- This message is shown when a file gets successfully uploaded. It's triggered by
    an event in dropzone.config.js. -->
    <div class="alert alert-success alert-dismissible fade in" style="display: none" id="upload_success_alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        File(s) successfully uploaded. Please <a class="alert-link" href="{{ app.request.uri }}">refresh</a> the page to see it in the list.
    </div>
{% endblock %}

{% block javascripts %}
<script src="{{ asset('js/dropzone.js') }}"></script>
<script src="{{ asset('js/dropzone.config.js') }}"></script>
{% endblock %}